import { Project } from "@/types/project";
import { completed, ongoing } from "@/assets/Projects";

export const projects: Project[] = [
  // Ongoing Projects
  {
    id: "ongoing-1",
    title: "Shelter Allahdad",
    location: "Jolshiri",
    status: "ongoing",
    image: ongoing.shelterAllahdadJolshiri.allahdad1, // Using first available image
    description: "Modern residential complex in Jolshiri with state-of-the-art amenities.",
    type: "Residential",
    completionDate: "2025",
    brochureUrl: "#", // Placeholder for brochure
  },
  {
    id: "ongoing-2",
    title: "Shelter NN Pinnacle",
    location: "AftabNagar",
    status: "ongoing",
    image: ongoing.shelterNnPinnacleAftabnagar._01NnPinnacle8d,
    description: "Luxury living spaces in the heart of AftabNagar.",
    type: "Residential",
    completionDate: "2025",
    brochureUrl: "#",
  },
  {
    id: "ongoing-3",
    title: "Shelter Valencia",
    location: "Bashundhara",
    status: "ongoing",
    image: ongoing.shelterValenciaBashundhara.shelterValenciaRevised,
    description: "Premium apartments designed for comfort and style in Bashundhara.",
    type: "Residential",
    completionDate: "2024",
    brochureUrl: "#",
  },

  // Completed Projects
  {
    id: "completed-1",
    title: "Amin Garden",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterAminGarden,
    description: "Completed residential project offering serene living spaces.",
    type: "Residential",
  },
  {
    id: "completed-2",
    title: "Ashraf Tower",
    location: "North Basabo",
    status: "completed",
    image: completed.shelterAshrafTowerNorthBasabo,
    description: "Commercial and residential tower in North Basabo.",
    type: "Mixed-Use",
  },
  {
    id: "completed-3",
    title: "Darasat Farida Mansion",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterDarasatFaridaMansion,
    description: "Elegant family residences.",
    type: "Residential",
  },
  {
    id: "completed-4",
    title: "Hafez Sharif Tayeba Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterHafezSharifTayebaTower,
    description: "Modern architectural design.",
    type: "Residential",
  },
  {
    id: "completed-5",
    title: "Honey Garden",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterHoneyGarden,
    description: "A peaceful retreat in the city.",
    type: "Residential",
  },
  {
    id: "completed-6",
    title: "Jamal Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterJamalTower,
    description: "High-rise living with great views.",
    type: "Residential",
  },
  {
    id: "completed-7",
    title: "Khaza Dreams",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterKhazaDreams,
    description: "Dream homes for modern families.",
    type: "Residential",
  },
  {
    id: "completed-8",
    title: "Laxmi Kunja",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterLaxmiKunja,
    description: "Traditional aesthetics met with modern comfort.",
    type: "Residential",
  },
  {
    id: "completed-9",
    title: "Mollah Villa",
    location: "Mirpur 1",
    status: "completed",
    image: completed.shelterMollahVillaMirpur1,
    description: "Spacious villa apartments in Mirpur.",
    type: "Residential",
  },
  {
    id: "completed-10",
    title: "Noorjahan",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterNoorjahan,
    description: "Luxury apartments.",
    type: "Residential",
  },
  {
    id: "completed-11",
    title: "Plush Cottage",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterPlushCottage,
    description: "Cozy and luxurious cottages.",
    type: "Residential",
  },
  {
    id: "completed-12",
    title: "Sarwar Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterSarwarTower,
    description: "Iconic tower in the city skyline.",
    type: "Residential",
  },
  {
    id: "completed-13",
    title: "Sopna Villa",
    location: "Nikunjo 2",
    status: "completed",
    image: completed.shelterSopnaVillaNikunjo2,
    description: "Premium villa in Nikunjo.",
    type: "Residential",
  },
  {
    id: "completed-14",
    title: "Sultana Garden",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterSultanaGarden,
    description: "Garden style living.",
    type: "Residential",
  },
  {
    id: "completed-15",
    title: "Sultana Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterSultanaTower,
    description: "Modern tower amenities.",
    type: "Residential",
  },
  {
    id: "completed-16",
    title: "Shelter View",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterView,
    description: "Apartments with a view.",
    type: "Residential",
  },
  {
    id: "completed-17",
    title: "Yousuf Villa",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterYousufVilla,
    description: "Classic villa design.",
    type: "Residential",
  },
];