import { Project } from "@/types/project";
import { completed, ongoing } from "@/assets/Projects";

export const projects: Project[] = [
  // Ongoing Projects
  {
    id: "ongoing-1",
    title: "Shelter Allahdad",
    location: "Jolshiri",
    status: "ongoing",
    image: ongoing.shelterAllahdadJolshiri.allahdad1,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
    completionDate: "2025",
    brochureUrl: "#",
  },
  {
    id: "ongoing-2",
    title: "Shelter NN Pinnacle",
    location: "AftabNagar",
    status: "ongoing",
    image: ongoing.shelterNnPinnacleAftabnagar._01NnPinnacle8d,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
    completionDate: "2025",
    brochureUrl: "#",
  },
  {
    id: "ongoing-3",
    title: "Shelter Valencia",
    location: "Bashundhara",
    status: "ongoing",
    image: ongoing.shelterValenciaBashundhara.shelterValenciaRevised,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
    completionDate: "2024",
    brochureUrl: "#",
  },

  // Completed Projects
  {
    id: "completed-1",
    title: "Shelter Amin Garden",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterAminGarden,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-2",
    title: "Shelter Ashraf Tower",
    location: "North Basabo",
    status: "completed",
    image: completed.shelterAshrafTowerNorthBasabo,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-3",
    title: "Shelter Darasat Farida Mansion",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterDarasatFaridaMansion,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-4",
    title: "Shelter Hafez Sharif Tayeba Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterHafezSharifTayebaTower,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-5",
    title: "Shelter Honey Garden",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterHoneyGarden,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-6",
    title: "Shelter Jamal Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterJamalTower,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-7",
    title: "Shelter Khaza Dreams",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterKhazaDreams,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-8",
    title: "Shelter Laxmi Kunja",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterLaxmiKunja,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-9",
    title: "Shelter Mollah Villa",
    location: "Mirpur 1",
    status: "completed",
    image: completed.shelterMollahVillaMirpur1,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-10",
    title: "Shelter Noorjahan",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterNoorjahan,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-11",
    title: "Shelter Plush Cottage",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterPlushCottage,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-12",
    title: "Shelter Sarwar Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterSarwarTower,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-13",
    title: "Shelter Sopna Villa",
    location: "Nikunjo 2",
    status: "completed",
    image: completed.shelterSopnaVillaNikunjo2,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-14",
    title: "Shelter Sultana Garden",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterSultanaGarden,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-15",
    title: "Shelter Sultana Tower",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterSultanaTower,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-16",
    title: "Shelter View",
    location: "Dhaka",
    status: "completed",
    image: completed.shelterView,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "completed-17",
    title: "Shelter Yousuf Villa",
    location: "Mohammadpur",
    status: "completed",
    image: completed.shelterYousufVilla,
    landArea: "5 Katha",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["Type-A 1220 sft", "Type-B 1150 sft"],
  },
];