import { Project, ProjectStatus, ElevatorType, ParkingAvailability } from "@/types/project";
import { completed, ongoing } from "@/assets/Projects";
import { logoMain } from "@/assets/Logo";
import { AllahdadBrochure } from "@/assets/Brochure";

export const projects: Project[] = [
  // Ongoing Projects
  {
    id: "ongoing-1",
    title: "Shelter Allahdad",
    location: "Plot 289, Road 7/B, Block E, Bashundhara R/A",
    status: ProjectStatus.ONGOING,
    image: ongoing.shelterAllahdadJolshiri.allahdad3,
    landArea: "12 Katha",
    buildingHeight: "G + 9",
    details: {
      elevator: ElevatorType.TWO,
      parking: ParkingAvailability.AVAILABLE,
      floors: "G + 9",
    },
    flatSizes: ["TBD"],
    completionDate: "2025",
    brochureUrl: AllahdadBrochure,
  },
  {
    id: "ongoing-2",
    title: "Shelter Valencia",
    location: "Plot 289, Road 7/B, Block E, Bashundhara R/A",
    status: ProjectStatus.ONGOING,
    image: ongoing.shelterValenciaBashundhara.shelterValenciaNight,
    landArea: "10 Katha",
    buildingHeight: "G + 9",
    flatSizes: ["Type-A 1700 sft", "Type-B 2300 sft"],
    details: {
      elevator: ElevatorType.TWO,
      parking: ParkingAvailability.AVAILABLE,
      floors: "G + 9",
    },
    completionDate: "2024",
    brochureUrl: "#",
  },
  // Upcoming Projects
  {
    id: "upcoming-1",
    title: "Shelter Kazi Mansion",
    location: "Road 10, Block L, Bashundhara R/A",
    status: ProjectStatus.UPCOMING,
    image: logoMain,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  {
    id: "upcoming-2",
    title: "Shelter Safara",
    location: "",
    status: ProjectStatus.UPCOMING,
    image: logoMain,
    landArea: "TBD",
    buildingHeight: "TBD",
    flatSizes: ["TBD"],
  },
  // Completed Projects
  {
    id: "completed-1",
    title: "Shelter NN Pinnacle",
    location: "Plot 31, Road 1, Sector 2, Aftabnagar",
    status: ProjectStatus.COMPLETED,
    image: ongoing.shelterNnPinnacleAftabnagar._01NnPinnacle8d,
    landArea: "8 Katha",
    buildingHeight: "G + 6",
    flatSizes: ["Type-A 1400 sft", "Type-B 1400 sft"],
    completionDate: "2024",
    brochureUrl: "#",
    details: {
      elevator: ElevatorType.AVAILABLE,
      parking: ParkingAvailability.AVAILABLE,
      floors: "G + 6",
    },
  },
  {
    id: "completed-2",
    title: "Shelter Amin Garden",
    location: "Bashundhara R/A, Block D",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterAminGarden,
    landArea: "5 Katha",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["Type-A 1350 sft", "Type-B 1350 sft"],
    details: {
      elevator: ElevatorType.AVAILABLE,
      parking: ParkingAvailability.AVAILABLE,
      floors: "G + 7",
    },
  },
  {
    id: "completed-3",
    title: "Shelter Ashraf Tower",
    location: "North Basabo",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterAshrafTowerNorthBasabo,
    landArea: "5 Katha",
    buildingHeight: "G+8 (9 Storied)",
    flatSizes: ["Type-A 1250 sft", "Type-B 1250 sft"],
  },
  {
    id: "completed-4",
    title: "Shelter Darasat Farida Mansion",
    location: "Malibag",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterDarasatFaridaMansion,
    landArea: "5 Katha",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["Type-A 1400 sft", "Type-B 1400 sft"],
  },
  {
    id: "completed-5",
    title: "Shelter Hafez Sharif Tayeba Tower",
    location: "Bakhshibazar",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterHafezSharifTayebaTower,
    landArea: "10 Katha",
    buildingHeight: "G+9 (10 Storied)",
    flatSizes: ["Type-A 1240 sft", "Type-B 1240 sft", "Type-C 1250 sft", "Type-D 1250 sft"],
  },
  {
    id: "completed-6",
    title: "Shelter Honey Garden",
    location: "Bashundhara R/A",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterHoneyGarden,
    landArea: "5 Katha",
    buildingHeight: "G+6 (7 Storied)",
    flatSizes: ["Type-A 1325 sft", "Type-B 1325 sft"],
  },
  {
    id: "completed-7",
    title: "Shelter Jamal Tower",
    location: "Bashundhara R/A",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterJamalTower,
    landArea: "5 Katha",
    buildingHeight: "G+6 (7 Storied)",
    flatSizes: ["Type-A 1350 sft", "Type-B 2700 sft"],
  },
  {
    id: "completed-8",
    title: "Shelter Khaza Dreams",
    location: "Bakhshibazar",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterKhazaDreams,
    landArea: "9 Katha",
    buildingHeight: "G+9 (10 Storied)",
    flatSizes: [
      "Type-A 1377 sft",
      "Type-B 1331 sft",
      "Type-C 1295 sft",
      "Type-D 1340 sft",
    ],
  },
  {
    id: "completed-9",
    title: "Shelter Laxmi Kunja",
    location: "Nikunja 2",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterLaxmiKunja,
    landArea: "2.5 Katha",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["Type-A 1620 sft"],
  },
  {
    id: "completed-10",
    title: "Shelter Mollah Villa",
    location: "Mirpur 1",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterMollahVillaMirpur1,
    landArea: "4 Katha",
    buildingHeight: "G+6 (7 Storied)",
    flatSizes: ["Type-A 1000 sft", "Type-B 1000 sft"],
  },
  {
    id: "completed-11",
    title: "Shelter Noorjahan",
    location: "Azimpur",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterNoorjahan,
    landArea: "9 Katha",
    buildingHeight: "G+9 (10 Storied)",
    flatSizes: [
      "Type-A 1150 sft",
      "Type-B 1150 sft",
      "Type-C 1150 sft",
      "Type-D 1150 sft",
    ],
  },
  {
    id: "completed-12",
    title: "Shelter Plush Cottage",
    location: "Banasree",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterPlushCottage,
    landArea: "5 Katha",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["Type-(A&B) 1325 sft"],
  },
  {
    id: "completed-13",
    title: "Shelter Sarwar Tower",
    location: "Naya Palton",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterSarwarTower,
    landArea: "5 Katha",
    buildingHeight: "G+8 (9 Storied)",
    flatSizes: ["Type-A 1325 sft", "Type-B 1310 sft"],
  },
  {
    id: "completed-14",
    title: "Shelter Sopna Villa",
    location: "Nikunjo 2",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterSopnaVillaNikunjo2,
    landArea: "2.5 Kathat",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["A 2750 sft"],
  },
  {
    id: "completed-15",
    title: "Shelter Sultana Garden",
    location: "North Basabo",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterSultanaGarden,
    landArea: "5 Katha",
    buildingHeight: "G+8 (9 Storied)",
    flatSizes: ["Type-A 1205 sft", "Type-A 1165 sft"],
  },
  {
    id: "completed-16",
    title: "Shelter Sultana Tower",
    location: "North Basabo",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterSultanaTower,
    landArea: "7 Katha",
    buildingHeight: "G+8 (9 Storied)",
    flatSizes: ["Type-A 1200 sft", "Type-B 1100 sft", "Type-C 1160 sft"],
  },
  {
    id: "completed-17",
    title: "Shelter View",
    location: "Banasree",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterView,
    landArea: "5 Katha",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["Type-(A&B) 1490 sft"],
  },
  {
    id: "completed-18",
    title: "Shelter Yousuf Villa",
    location: "Mohammadpur",
    status: ProjectStatus.COMPLETED,
    image: completed.shelterYousufVilla,
    landArea: "5 Katha",
    buildingHeight: "G+7 (8 Storied)",
    flatSizes: ["Type-A 1220 sft", "Type-B 1150 sft"],
  },

];